// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3FMCO67cL6-YNzSj9kfPz4yeM4oKivwQ',
    appId: '1:810133282395:web:5681c3cccb226261f8297e',
    messagingSenderId: '810133282395',
    projectId: 'eco-habit-tracker-8e25c',
    authDomain: 'eco-habit-tracker-8e25c.firebaseapp.com',
    storageBucket: 'eco-habit-tracker-8e25c.firebasestorage.app',
    measurementId: 'G-GXFM27YQZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAczFuwTsJJDSASZdMMfjDPBcNE_eGfPoI',
    appId: '1:810133282395:android:2d142e92367690edf8297e',
    messagingSenderId: '810133282395',
    projectId: 'eco-habit-tracker-8e25c',
    storageBucket: 'eco-habit-tracker-8e25c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5cv8ZlZoe2o2FasPzcYVu0pP6wfyGi7Y',
    appId: '1:810133282395:ios:d2972733ffd62a8df8297e',
    messagingSenderId: '810133282395',
    projectId: 'eco-habit-tracker-8e25c',
    storageBucket: 'eco-habit-tracker-8e25c.firebasestorage.app',
    iosBundleId: 'com.example.f1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5cv8ZlZoe2o2FasPzcYVu0pP6wfyGi7Y',
    appId: '1:810133282395:ios:d2972733ffd62a8df8297e',
    messagingSenderId: '810133282395',
    projectId: 'eco-habit-tracker-8e25c',
    storageBucket: 'eco-habit-tracker-8e25c.firebasestorage.app',
    iosBundleId: 'com.example.f1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3FMCO67cL6-YNzSj9kfPz4yeM4oKivwQ',
    appId: '1:810133282395:web:d0e746bede5306e5f8297e',
    messagingSenderId: '810133282395',
    projectId: 'eco-habit-tracker-8e25c',
    authDomain: 'eco-habit-tracker-8e25c.firebaseapp.com',
    storageBucket: 'eco-habit-tracker-8e25c.firebasestorage.app',
    measurementId: 'G-PD9648LLPE',
  );
}
